package cefet.view;

import cefet.controller.AndarilhoJpaController;
import cefet.controller.exceptions.NonexistentEntityException;
import cefet.persistence.PersistenceSingleton;
import cefetmg.model.Andarilho;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alunos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        inputNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelDtNasc = new javax.swing.JLabel();
        labelTel = new javax.swing.JLabel();
        labelEnd = new javax.swing.JLabel();
        inputDtNasc = new javax.swing.JTextField();
        inputTel = new javax.swing.JTextField();
        inputEnd = new javax.swing.JTextField();
        buttonAdicionar = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        labelNome.setText("Nome:");

        labelDtNasc.setText("Data Nascimento:");

        labelTel.setText("Telefone:");

        labelEnd.setText("Endereço:");

        buttonAdicionar.setText("Adicionar");
        buttonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarActionPerformed(evt);
            }
        });

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonRemover.setText("Remover");
        buttonRemover.setToolTipText("");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        tableDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1", "1", "1"},
                {"2", "2", "2", "2"},
                {"3", "3", "3", "3"},
                {"4", "4", "4", "4"}
            },
            new String [] {
                "Nome", "Data Nascimento", "Telefone", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(tableDados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAdicionar)
                .addGap(18, 18, 18)
                .addComponent(buttonSalvar)
                .addGap(18, 18, 18)
                .addComponent(buttonRemover)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEnd)
                        .addGap(67, 67, 67)
                        .addComponent(inputEnd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDtNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDtNasc))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addGap(93, 93, 93)
                        .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTel)
                        .addGap(71, 71, 71)
                        .addComponent(inputTel)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDtNasc)
                    .addComponent(inputDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTel)
                    .addComponent(inputTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnd)
                    .addComponent(inputEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionar)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tableDados.getModel();
        int rowSelected = tableDados.getSelectedRow();
        String nome, dtNasc, tel, end;
        nome=inputNome.getText();
        dtNasc=inputDtNasc.getText();
        tel=inputTel.getText();
        end=inputEnd.getText();
        if(rowSelected == -1){
            comportamentoAdd();
        }
        else{
            dtm.setValueAt(nome, rowSelected, 0);
            dtm.setValueAt(dtNasc, rowSelected, 1);
            dtm.setValueAt(tel, rowSelected, 2);
            dtm.setValueAt(end, rowSelected, 3);  
            EntityManagerFactory ponte = PersistenceSingleton.getInstance().getEntityManagerFactory();
            
            AndarilhoJpaController andarilhoController = new AndarilhoJpaController(ponte);

            Andarilho usu1 = new Andarilho();
            usu1.setNome(nome);
            usu1.setDtNasc(dtNasc);
            usu1.setTelefone(tel);
            usu1.setEndereco(end);
            
            try{
                andarilhoController.edit(usu1);
                
            }
            catch(NonexistentEntityException e){
                System.out.println("Erro! ID inexistente!");
            }
            catch(Exception e){
                System.out.println("Erro!");
            }
        }
        
    }                                            

    private void buttonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        comportamentoAdd();
    }                                               

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel) tableDados.getModel();
        int rowSelected=tableDados.getSelectedRow();
        
            if(rowSelected==-1){
               JOptionPane.showMessageDialog(this, "Selecione a linha que quer remover antes de clicar no botão!");
            }
            else{
                
                int opcao = JOptionPane.showConfirmDialog(this,"Tem certeza que deseja remover a linha selecionada?","Confirme sua operação", JOptionPane.YES_NO_OPTION);
                
                if (opcao==JOptionPane.YES_OPTION)
                    dtm.removeRow(rowSelected);
            }
    }                                             

    public void comportamentoAdd(){
        String nome, dataNascimento, telefone, endereco;
        nome=inputNome.getText();
        dataNascimento=inputDtNasc.getText();
        telefone=inputTel.getText();
        endereco=inputEnd.getText();
        if(nome.equals("") || dataNascimento.equals("") || telefone.equals("") || endereco.equals("")){
            JOptionPane.showMessageDialog(this, "Campo Nome, Data Nascimento, Telefone e Endereço são de preenchimentos obrigatórios");
        }
        else{
            DefaultTableModel dtm= (DefaultTableModel) tableDados.getModel();
            String a []= new String[] {nome,dataNascimento,telefone,endereco};
            dtm.addRow(a);
        
            EntityManagerFactory ponte = PersistenceSingleton.getInstance().getEntityManagerFactory();
            
            
            AndarilhoJpaController andarilhoController = new AndarilhoJpaController(ponte);
            
            Andarilho usu1 = new Andarilho();
            usu1.setNome(nome);
            usu1.setDtNasc(dataNascimento);
            usu1.setEndereco(endereco);
            usu1.setTelefone(telefone);
            andarilhoController.create(usu1);
            
            System.out.println(usu1.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JTextField inputDtNasc;
    private javax.swing.JTextField inputEnd;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputTel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDtNasc;
    private javax.swing.JLabel labelEnd;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTel;
    private javax.swing.JTable tableDados;
    // End of variables declaration                   
}
